language: cpp
dist: trusty
sudo: required

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-6 CMAKE_BUILD_TYPE=Release ENABLE_BLOB_SUPPORT=0 ENABLE_CPP11_SUPPORT=0
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-6, gcc-6, curl, libcurl4-openssl-dev]

    - os: linux
      compiler: gcc
      env: COMPILER=g++-6 CMAKE_BUILD_TYPE=Release ENABLE_BLOB_SUPPORT=1 ENABLE_CPP11_SUPPORT=0
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-6, gcc-6, curl, libcurl4-openssl-dev]

    - os: linux
      compiler: gcc
      env: COMPILER=g++-6 CMAKE_BUILD_TYPE=Release ENABLE_BLOB_SUPPORT=0 ENABLE_CPP11_SUPPORT=1
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-6, gcc-6, curl, libcurl4-openssl-dev]

    - os: linux
      compiler: gcc
      env: COMPILER=g++-6 CMAKE_BUILD_TYPE=Release ENABLE_BLOB_SUPPORT=1 ENABLE_CPP11_SUPPORT=1
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-6, gcc-6, curl, libcurl4-openssl-dev]

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_COMPILER=$COMPILER .. && make
