language: cpp
dist: trusty
sudo: required

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6 CXX_FLAGS="-std=c++98" ENABLE_BLOB_SUPPORT=0 ENABLE_CPP11_SUPPORT=0
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-6, curl, libcurl4-openssl-dev]

    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6 CXX_FLAGS="-std=c++98" ENABLE_BLOB_SUPPORT=1 ENABLE_CPP11_SUPPORT=0
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-6, curl, libcurl4-openssl-dev]

    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6 CXX_FLAGS="-std=c++11" ENABLE_BLOB_SUPPORT=0 ENABLE_CPP11_SUPPORT=1
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-6, curl, libcurl4-openssl-dev]

    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6 CXX_FLAGS="-std=c++11" ENABLE_BLOB_SUPPORT=1 ENABLE_CPP11_SUPPORT=1
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-6, curl, libcurl4-openssl-dev]

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON .. && make
